apiVersion: apps/v1
kind: Deployment
metadata:
  name: anoopanu
  labels:
    app: anoopanu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anoopanu
  template:
    metadata:
      labels:
        app: anoopanu
    spec:
      containers:
        - name: dockerimageanu
          image: 418726154740.dkr.ecr.us-east-2.amazonaws.com/dockerimageanu
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
